export {
  console_log_safe,
  console_warn_safe,
  console_error_safe,
  console_debug_safe,
  log,
  warn,
  error,
  exc,
  debug,
  clog,
  cwarn,
  cerror,
  cexc,
  cdebug,
  setLogHandler,
  setWarnHandler,
  setErrorHandler,
  setDebugHandler,
} from "./logging";

export {
  getHexUUID,
  getSecureRandomBytes,
  getSecureRandomString,
  xorString,
  u8,
  xor,
  gendigest,
} from "./crypto";

export {
  getPlatformProcessor,
  getPlatformName,
  getFirstBrowserLanguage,
  getKeyboardLayout,
  isMacOS,
  isWindows,
  isFirefox,
  isOpera,
  isSafari,
  isWebkit,
  isEdge,
  isChrome,
  isIE,
  getBrowserName,
  getOS,
  is64bit,
  isMobile,
  getSimpleUserAgentString,
  getColorGamut,
  isEventSupported,
  normalizeWheel,
  getConnectionInfo,
  saveFile,
  type NormalizedWheel,
} from "./platform";

export {
  stristrue,
  removeChars,
  trimString,
  convertToHex,
  hexToString,
  arrayhex,
  hexarray,
  StringToUint8,
  Uint8ToString,
  s,
  u,
  ArrayBufferToString,
  ArrayBufferToBase64,
  ToBase64,
  convertDataURIToBinary,
  parseINIString,
  ParseResponseHeaders,
  parseParams,
} from "./encoding";

export {
  isSafeHost,
  hasSessionStorage,
  getSessionStoragePrefix,
  getSessionStorageValue,
  setSessionStorageValue,
  clearSessionStorage,
  getparam,
  jsonAction,
} from "./storage";
