/*
 * Author: Ali Parnan
 */

export const MOVERESIZE_SIZE_TOPLEFT = 0;
export const MOVERESIZE_SIZE_TOP = 1;
export const MOVERESIZE_SIZE_TOPRIGHT = 2;
export const MOVERESIZE_SIZE_RIGHT = 3;
export const MOVERESIZE_SIZE_BOTTOMRIGHT = 4;
export const MOVERESIZE_SIZE_BOTTOM = 5;
export const MOVERESIZE_SIZE_BOTTOMLEFT = 6;
export const MOVERESIZE_SIZE_LEFT = 7;
export const MOVERESIZE_MOVE = 8;
export const MOVERESIZE_SIZE_KEYBOARD = 9;
export const MOVERESIZE_MOVE_KEYBOARD = 10;
export const MOVERESIZE_CANCEL = 11;

export const MOVERESIZE_DIRECTION_STRING: Readonly<Record<number, string>> = {
  [MOVERESIZE_SIZE_TOPLEFT]: "SIZE_TOPLEFT",
  [MOVERESIZE_SIZE_TOP]: "SIZE_TOP",
  [MOVERESIZE_SIZE_TOPRIGHT]: "SIZE_TOPRIGHT",
  [MOVERESIZE_SIZE_RIGHT]: "SIZE_RIGHT",
  [MOVERESIZE_SIZE_BOTTOMRIGHT]: "SIZE_BOTTOMRIGHT",
  [MOVERESIZE_SIZE_BOTTOM]: "SIZE_BOTTOM",
  [MOVERESIZE_SIZE_BOTTOMLEFT]: "SIZE_BOTTOMLEFT",
  [MOVERESIZE_SIZE_LEFT]: "SIZE_LEFT",
  [MOVERESIZE_MOVE]: "MOVE",
  [MOVERESIZE_SIZE_KEYBOARD]: "SIZE_KEYBOARD",
  [MOVERESIZE_MOVE_KEYBOARD]: "MOVE_KEYBOARD",
  [MOVERESIZE_CANCEL]: "CANCEL",
};

export const MOVERESIZE_DIRECTION_JS_NAME: Readonly<Record<number, string>> = {
  [MOVERESIZE_SIZE_TOPLEFT]: "nw",
  [MOVERESIZE_SIZE_TOP]: "n",
  [MOVERESIZE_SIZE_TOPRIGHT]: "ne",
  [MOVERESIZE_SIZE_RIGHT]: "e",
  [MOVERESIZE_SIZE_BOTTOMRIGHT]: "se",
  [MOVERESIZE_SIZE_BOTTOM]: "s",
  [MOVERESIZE_SIZE_BOTTOMLEFT]: "sw",
  [MOVERESIZE_SIZE_LEFT]: "w",
};
